jobs:
  fisherman:
    display-name: "üêü Nelayan"
    prices:
      COD: 4.0
      SALMON: 6.0
      TROPICAL_FISH: 20.0
      PUFFERFISH: 35.0
      NAUTILUS_SHELL: 350.0

  farmer:
    display-name: "üå± Petani"
    prices:
      WHEAT: 0.8
      POTATO: 1.5
      CARROT: 1.5
      SUGAR_CANE: 2.0
      MELON_SLICE: 1.0
      PUMPKIN: 4.0
      NETHER_WART: 12.0

  miner:
    display-name: "‚õè Penambang"
    prices:
      COBBLESTONE: 0.2
      COAL: 4.0
      RAW_IRON: 8.0
      RAW_COPPER: 4.0
      RAW_GOLD: 18.0
      REDSTONE: 6.0
      LAPIS_LAZULI: 7.0
      DIAMOND: 120.0
      EMERALD: 140.0
      ANCIENT_DEBRIS: 1200.0

  lumberjack:
    display-name: "ü™ì Penebang Kayu"
    prices:
      OAK_LOG: 1.5
      SPRUCE_LOG: 1.5
      BIRCH_LOG: 1.5
      JUNGLE_LOG: 1.5
      ACACIA_LOG: 1.5
      DARK_OAK_LOG: 1.5
      MANGROVE_LOG: 1.5
      CHERRY_LOG: 1.8
      PALE_OAK_LOG: 1.8

  hunter:
    display-name: "üèπ Pemburu"
    prices:
      ROTTEN_FLESH: 0.1
      BONE: 4.0
      STRING: 4.0
      SPIDER_EYE: 4.0
      GUNPOWDER: 9.0
      ENDER_PEARL: 45.0
      BLAZE_ROD: 90.0
      WITHER_SKELETON_SKULL: 7000.0

  smelter:
    display-name: "üî• Smelter"
    prices:
      IRON_INGOT: 14.0
      COPPER_INGOT: 7.0
      GOLD_INGOT: 28.0
      NETHERITE_SCRAP: 650.0
      GLASS: 1.5
      SMOOTH_STONE: 0.8

  breeder:
    display-name: "üêÑ Peternak"
    prices:
      BEEF: 5.0
      PORKCHOP: 5.0
      MUTTON: 5.0
      CHICKEN: 4.0
      RABBIT: 7.0
      MILK_BUCKET: 12.0
      EGG: 2.0
      LEATHER: 9.0
      FEATHER: 3.0

  cook:
    display-name: "üç≥ Pemasak"
    prices:
      BREAD: 3.5
      BAKED_POTATO: 4.0
      COOKED_BEEF: 9.0
      COOKED_PORKCHOP: 9.0
      COOKED_CHICKEN: 7.0
      COOKED_MUTTON: 8.0
      COOKED_RABBIT: 11.0
      PUMPKIN_PIE: 18.0
      CAKE: 45.0

leave:
  price: 400.0